spring:
  config:
    activate:
      on-profile: local

#  datasource:
#    url: jdbc:h2:mem:demo;MODE=MySQL;DB_CLOSE_DELAY=-1
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver

management:
  endpoint:
    health:
      show-details: always
