spring:
  config:
    activate:
      on-profile: prod

#  datasource:
#    url: jdbc:h2:mem:demo;MODE=MySQL;DB_CLOSE_DELAY=-1
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver

#logging:
#  level:
#    root: INFO

management:
  endpoint:
    health:
      show-details: never
