version: "3.8"
services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: item
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: local
    restart: always